name = "common-room"
compatibility_date = "2026-09-01"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "common-room-comments"
database_id = "9fbc29b6-2e9e-44da-94d7-ea1f306833ca"
migrations_dir = "migrations"
